version:
  '3'

tasks:
  build:
    desc: "Build the project"
    cmds:
      - go build -o bbc
    deps:
      - generate

  build-linux:
    desc: "Build the project for Linux"
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o bbc-linux
    deps:
      - generate

  generate:
    desc: "Generate code"
    cmds:
      - go generate ./...
    sources:
      - app/bbclient/bbclient.json
      - app/bbclient/config.yaml
    generates:
      - app/bbclient/*.gen.go